const fs = require('fs');
const path = require('path');

console.log('\n🎨 Building JP AUTO brand system...\n');

// Read tokens
const tokens = require('./tokens.json');

// Create dist directory
const distDir = path.join(__dirname, 'dist');
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir, { recursive: true });
}

// 1. Generate CSS Variables
let cssContent = `:root {\n`;

// Add color tokens
Object.keys(tokens.color || {}).forEach(key => {
  const token = tokens.color[key];
  const comment = token.description ? `  /* ${token.description} */\n` : '';
  cssContent += `${comment}  --color-${key}: ${token.value};\n`;
});

// Add gradient tokens
Object.keys(tokens.gradient || {}).forEach(key => {
  const token = tokens.gradient[key];
  const comment = token.description ? `  /* ${token.description} */\n` : '';
  cssContent += `${comment}  --gradient-${key}: ${token.value};\n`;
});

// Add shadow tokens
Object.keys(tokens.shadow || {}).forEach(key => {
  const token = tokens.shadow[key];
  const comment = token.description ? `  /* ${token.description} */\n` : '';
  cssContent += `${comment}  --shadow-${key}: ${token.value};\n`;
});

// Add spacing tokens
Object.keys(tokens.spacing || {}).forEach(key => {
  const token = tokens.spacing[key];
  const comment = token.description ? `  /* ${token.description} */\n` : '';
  cssContent += `${comment}  --spacing-${key}: ${token.value};\n`;
});

// Add radius tokens
Object.keys(tokens.radius || {}).forEach(key => {
  const token = tokens.radius[key];
  const comment = token.description ? `  /* ${token.description} */\n` : '';
  cssContent += `${comment}  --radius-${key}: ${token.value};\n`;
});

// Add typography tokens
if (tokens.typography && tokens.typography['font-family']) {
  Object.keys(tokens.typography['font-family']).forEach(key => {
    const token = tokens.typography['font-family'][key];
    const comment = token.description ? `  /* ${token.description} */\n` : '';
    cssContent += `${comment}  --font-family-${key}: ${token.value};\n`;
  });
}

if (tokens.typography && tokens.typography['font-weight']) {
  Object.keys(tokens.typography['font-weight']).forEach(key => {
    const token = tokens.typography['font-weight'][key];
    const comment = token.description ? `  /* ${token.description} */\n` : '';
    cssContent += `${comment}  --font-weight-${key}: ${token.value};\n`;
  });
}

cssContent += `}\n\n`;

// Add utility classes for gradients
cssContent += `/* Utility classes for pearlescent effects */\n`;
cssContent += `.bg-primary-pearlescent {
  background: var(--gradient-pearlescent-primary);
  background-size: 200% 200%;
  animation: shimmer 3s ease-in-out infinite;
}

.bg-background-pearlescent {
  background: var(--gradient-pearlescent-background);
  background-size: 200% 200%;
  animation: shimmer 3s ease-in-out infinite;
}

@keyframes shimmer {
  0%, 100% {
    background-position: 0% 50%;
  }
  50% {
    background-position: 100% 50%;
  }
}
`;

fs.writeFileSync(path.join(distDir, 'brand.css'), cssContent);

// 2. Generate Tailwind Config
const colors = {};
const spacing = {};
const borderRadius = {};
const boxShadow = {};

Object.keys(tokens.color || {}).forEach(key => {
  colors[key] = tokens.color[key].hex || tokens.color[key].value;
});

Object.keys(tokens.spacing || {}).forEach(key => {
  spacing[key] = tokens.spacing[key].value;
});

Object.keys(tokens.radius || {}).forEach(key => {
  borderRadius[key] = tokens.radius[key].value;
});

Object.keys(tokens.shadow || {}).forEach(key => {
  boxShadow[key] = tokens.shadow[key].value;
});

const tailwindConfig = `// Auto-generated by JP AUTO brand system - DO NOT EDIT MANUALLY
// Edit brand/tokens.json and run 'npm run build' instead

module.exports = {
  colors: ${JSON.stringify(colors, null, 2)},
  spacing: ${JSON.stringify(spacing, null, 2)},
  borderRadius: ${JSON.stringify(borderRadius, null, 2)},
  boxShadow: ${JSON.stringify(boxShadow, null, 2)}
};
`;

fs.writeFileSync(path.join(distDir, 'tailwind.config.js'), tailwindConfig);

// 3. Generate JavaScript exports
const jsContent = `// Auto-generated by JP AUTO brand system - DO NOT EDIT MANUALLY
// Edit brand/tokens.json and run 'npm run build' instead

export const colors = ${JSON.stringify(colors, null, 2)};
export const spacing = ${JSON.stringify(spacing, null, 2)};
export const borderRadius = ${JSON.stringify(borderRadius, null, 2)};
export const boxShadow = ${JSON.stringify(boxShadow, null, 2)};

export default {
  colors,
  spacing,
  borderRadius,
  boxShadow
};
`;

fs.writeFileSync(path.join(distDir, 'tokens.js'), jsContent);

// 4. Generate HTML Documentation
const colorRows = Object.keys(tokens.color || {}).map(key => {
  const token = tokens.color[key];
  return `
      <tr>
        <td><code>--color-${key}</code></td>
        <td>
          <div style="display: inline-block; width: 40px; height: 40px; background: ${token.value}; border: 1px solid #ccc; border-radius: 4px; vertical-align: middle;"></div>
        </td>
        <td><code>${token.hex || token.value}</code></td>
        <td>${token.description || ''}</td>
      </tr>
    `;
}).join('');

const gradientRows = Object.keys(tokens.gradient || {}).map(key => {
  const token = tokens.gradient[key];
  return `
      <tr>
        <td><code>--gradient-${key}</code></td>
        <td>
          <div style="width: 200px; height: 40px; background: ${token.value}; border: 1px solid #ccc; border-radius: 4px;"></div>
        </td>
        <td><code style="font-size: 10px;">${token.value.substring(0, 60)}...</code></td>
        <td>${token.description || ''}</td>
      </tr>
    `;
}).join('');

const shadowRows = Object.keys(tokens.shadow || {}).map(key => {
  const token = tokens.shadow[key];
  return `
      <tr>
        <td><code>--shadow-${key}</code></td>
        <td>
          <div style="display: inline-block; width: 80px; height: 40px; background: white; box-shadow: ${token.value}; border-radius: 4px;"></div>
        </td>
        <td><code style="font-size: 10px;">${token.value}</code></td>
        <td>${token.description || ''}</td>
      </tr>
    `;
}).join('');

const docsHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>JP AUTO Brand Guide</title>

  <!-- Google Fonts - Range Rover inspired typography -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&family=Nunito+Sans:wght@300;400;600;700;800&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="brand.css">
  <style>
    body {
      font-family: 'Montserrat', 'Lato', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 40px 20px;
      background: #f5f5f5;
    }
    h1, h2, h3, h4, h5, h6 {
      font-family: 'Nunito Sans', 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    }
    h1 {
      color: var(--color-primary);
      border-bottom: 3px solid var(--color-primary);
      padding-bottom: 10px;
    }
    h2 {
      color: #333;
      margin-top: 40px;
      padding-bottom: 8px;
      border-bottom: 2px solid #ddd;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      background: white;
      margin: 20px 0;
      box-shadow: var(--shadow-md);
    }
    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #eee;
    }
    th {
      background: var(--color-primary);
      color: white;
      font-weight: 600;
    }
    code {
      background: #f0f0f0;
      padding: 2px 6px;
      border-radius: 3px;
      font-size: 13px;
    }
    .brand-header {
      text-align: center;
      padding: 60px 20px;
      background: var(--gradient-pearlescent-primary);
      color: white;
      border-radius: var(--radius-lg);
      margin-bottom: 40px;
      background-size: 200% 200%;
      animation: shimmer 3s ease-in-out infinite;
    }
    .brand-header h1 {
      color: white;
      border: none;
      margin: 0;
      font-size: 48px;
    }
    .brand-header p {
      font-size: 18px;
      opacity: 0.9;
      margin-top: 10px;
    }
  </style>
</head>
<body>
  <div class="brand-header">
    <h1>JP AUTO Brand Guide</h1>
    <p>Design tokens and brand system</p>
    <p style="font-size: 14px; margin-top: 20px;">Generated on ${new Date().toLocaleDateString()}</p>
  </div>

  <h2>Colors</h2>
  <table>
    <thead>
      <tr>
        <th>Token Name</th>
        <th>Preview</th>
        <th>Value</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      ${colorRows}
    </tbody>
  </table>

  <h2>Gradients (Pearlescent Effects)</h2>
  <table>
    <thead>
      <tr>
        <th>Token Name</th>
        <th>Preview</th>
        <th>Value</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      ${gradientRows}
    </tbody>
  </table>

  <h2>Shadows</h2>
  <table>
    <thead>
      <tr>
        <th>Token Name</th>
        <th>Preview</th>
        <th>Value</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      ${shadowRows}
    </tbody>
  </table>

  <h2>Typography (Range Rover Inspired)</h2>
  <div style="background: white; padding: 20px; border-radius: var(--radius-md); margin-top: 20px;">
    <div style="margin-bottom: 30px;">
      <h3 style="margin-bottom: 15px;">Font Families</h3>
      <div style="margin-bottom: 20px; padding: 15px; background: #f9f9f9; border-left: 4px solid var(--color-primary);">
        <div style="margin-bottom: 10px;">
          <strong>Body Text:</strong> <code style="margin-left: 10px;">Montserrat</code>
          <div style="margin-top: 8px; font-family: 'Montserrat', sans-serif; font-size: 16px;">
            The quick brown fox jumps over the lazy dog. 0123456789
          </div>
        </div>
      </div>
      <div style="margin-bottom: 20px; padding: 15px; background: #f9f9f9; border-left: 4px solid var(--color-primary);">
        <div style="margin-bottom: 10px;">
          <strong>Headings:</strong> <code style="margin-left: 10px;">Nunito Sans</code>
          <div style="margin-top: 8px; font-family: 'Nunito Sans', sans-serif; font-size: 24px; font-weight: 700;">
            The quick brown fox jumps over the lazy dog
          </div>
        </div>
      </div>
      <div style="padding: 15px; background: #f9f9f9; border-left: 4px solid var(--color-primary);">
        <div style="margin-bottom: 10px;">
          <strong>Monospace:</strong> <code style="margin-left: 10px;">Courier Prime</code>
          <div style="margin-top: 8px; font-family: 'Courier Prime', monospace; font-size: 14px;">
            VIN: 1HGBH41JXMN109186
          </div>
        </div>
      </div>
    </div>

    <div>
      <h3 style="margin-bottom: 15px;">Font Weights</h3>
      <div style="font-family: 'Montserrat', sans-serif;">
        <div style="padding: 10px; border-bottom: 1px solid #eee;"><span style="font-weight: 300;">Light (300)</span> - The quick brown fox</div>
        <div style="padding: 10px; border-bottom: 1px solid #eee;"><span style="font-weight: 400;">Normal (400)</span> - The quick brown fox</div>
        <div style="padding: 10px; border-bottom: 1px solid #eee;"><span style="font-weight: 500;">Medium (500)</span> - The quick brown fox</div>
        <div style="padding: 10px; border-bottom: 1px solid #eee;"><span style="font-weight: 600;">Semibold (600)</span> - The quick brown fox</div>
        <div style="padding: 10px; border-bottom: 1px solid #eee;"><span style="font-weight: 700;">Bold (700)</span> - The quick brown fox</div>
        <div style="padding: 10px;"><span style="font-weight: 800;">Extra Bold (800)</span> - The quick brown fox</div>
      </div>
    </div>
  </div>

  <h2>Usage</h2>
  <div style="background: white; padding: 20px; border-radius: var(--radius-md); margin-top: 20px;">
    <h3>CSS Variables</h3>
    <pre><code>&lt;!-- Import the brand CSS file --&gt;
&lt;link rel="stylesheet" href="../brand/dist/brand.css"&gt;

&lt;!-- Use CSS variables --&gt;
&lt;style&gt;
.element {
  background: var(--color-background);
  color: var(--color-foreground);
  border: 1px solid var(--color-border);
}

.button {
  background: var(--color-primary);
  box-shadow: var(--shadow-md);
  border-radius: var(--radius-md);
}

/* Pearlescent button */
.button-pearlescent {
  background: var(--gradient-pearlescent-primary);
  background-size: 200% 200%;
  animation: shimmer 3s ease-in-out infinite;
}
&lt;/style&gt;</code></pre>

    <h3>Tailwind CSS</h3>
    <pre><code>// Import in tailwind.config.js
const brand = require('./brand/dist/tailwind.config.js');

module.exports = {
  theme: {
    extend: {
      colors: brand.colors,
      spacing: brand.spacing,
      borderRadius: brand.borderRadius,
      boxShadow: brand.boxShadow
    }
  }
}

// Then use in HTML:
&lt;div class="bg-primary text-white rounded-lg shadow-md"&gt;
  Styled with brand tokens!
&lt;/div&gt;</code></pre>

    <h3>Inline Tailwind Config (for CDN)</h3>
    <pre><code>&lt;script&gt;
  tailwind.config = {
    theme: {
      extend: {
        colors: {
          'background': '${colors.background}',
          'primary': '${colors.primary}',
          'primary-dark': '${colors['primary-dark']}',
          'foreground': '${colors.foreground}'
        }
      }
    }
  }
&lt;/script&gt;</code></pre>
  </div>
</body>
</html>`;

fs.writeFileSync(path.join(distDir, 'index.html'), docsHTML);

// 5. Generate README
const readme = `# JP AUTO Brand System

This is the centralized brand system for JP AUTO. All colors, spacing, and design tokens are defined here.

## Files

- **tokens.json** - Source of truth for all brand tokens
- **dist/brand.css** - CSS variables for all tokens
- **dist/tokens.js** - JavaScript/ES6 exports
- **dist/tailwind.config.js** - Tailwind configuration
- **dist/index.html** - Visual brand documentation

## Usage

### Option 1: CSS Variables (Recommended)

Import the CSS file in your HTML:

\`\`\`html
<link rel="stylesheet" href="../brand/dist/brand.css">
\`\`\`

Use variables in your CSS:

\`\`\`css
.element {
  background: var(--color-background);
  color: var(--color-foreground);
}
\`\`\`

### Option 2: Tailwind Config

Import in your \`tailwind.config.js\`:

\`\`\`javascript
const brand = require('./brand/dist/tailwind.config.js');

module.exports = {
  theme: {
    extend: {
      colors: brand.colors,
      spacing: brand.spacing,
      borderRadius: brand.borderRadius,
      boxShadow: brand.boxShadow
    }
  }
}
\`\`\`

### Option 3: Inline Tailwind (CDN)

\`\`\`html
<script>
  tailwind.config = {
    theme: {
      extend: {
        colors: {
          'primary': '${colors.primary}',
          'background': '${colors.background}'
        }
      }
    }
  }
</script>
\`\`\`

## Making Changes

1. Edit \`tokens.json\`
2. Run \`npm run build\`
3. All projects automatically use the updated tokens

## View Documentation

Open \`dist/index.html\` in a browser to see the visual brand guide.
`;

fs.writeFileSync(path.join(__dirname, 'README.md'), readme);

console.log('✅ Build complete! Generated files:');
console.log('   - dist/brand.css (CSS variables)');
console.log('   - dist/tokens.js (JavaScript exports)');
console.log('   - dist/tailwind.config.js (Tailwind configuration)');
console.log('   - dist/index.html (Brand documentation)');
console.log('   - README.md (Usage instructions)\n');
console.log('📖 Open dist/index.html to view the brand guide\n');
